export interface DestinationItem {
  id: number;
  city: string;
  type: string;
}

export interface Category {
  id: number;
  name: string;
  key: string;
  items: DestinationItem[];
}

export const categoriesData: Category[] = [
  {
    id: 1,
    name: "Popular",
    key: "popular",
    items: [
      { id: 1, city: "Marbella", type: "Holiday rentals" },
      { id: 2, city: "Cape Town", type: "Cottage rentals" },
      { id: 3, city: "Harrogate", type: "Serviced apartment rentals" },
      { id: 4, city: "Barcelona", type: "House rentals" },
      { id: 5, city: "Eastbourne", type: "Cottage rentals" },
      { id: 6, city: "Minorca", type: "Pet-friendly rentals" },
      { id: 7, city: "Tenby", type: "Flat rentals" },
      { id: 8, city: "Marseille", type: "Pet-friendly rentals" },
      { id: 9, city: "Nottingham", type: "Pet-friendly rentals" },
      { id: 10, city: "Exeter", type: "Villa rentals" },
      { id: 11, city: "Dubai", type: "Pet-friendly rentals" },
      { id: 12, city: "Weymouth", type: "Cottage rentals" },
      { id: 13, city: "Leicester", type: "Flat rentals" },
      { id: 14, city: "Lincoln", type: "Flat rentals" },
      { id: 15, city: "Athens", type: "Flat rentals" },
      { id: 16, city: "San Sebastián", type: "Serviced apartment rentals" },
      { id: 17, city: "Margate", type: "Pet-friendly rentals" }
    ]
  },
  {
    id: 2,
    name: "Coastal",
    key: "coastal",
    items: [
      { id: 101, city: "Patong Beach", type: "Monthly Rentals" },
      { id: 102, city: "Fareham", type: "House rentals" },
      { id: 103, city: "Benllech", type: "House rentals" },
      { id: 104, city: "Carnoustie", type: "Cottage rentals" },
      { id: 105, city: "Alpúdia", type: "House rentals" },
      { id: 106, city: "Newbiggin-by-the-Sea", type: "Monthly Rentals" },
      { id: 107, city: "Criccieth", type: "Holiday rentals" },
      { id: 108, city: "Braunton", type: "Cottage rentals" },
      { id: 109, city: "Fistral Beach", type: "Cottage rentals" },
      { id: 110, city: "Portsmouth", type: "Villa rentals" },
      { id: 111, city: "Sarasota", type: "Cottage rentals" },
      { id: 112, city: "Savannah", type: "Monthly Rentals" },
      { id: 113, city: "San Francisco", type: "Serviced apartment rentals" },
      { id: 114, city: "Cocoa Beach", type: "House rentals" },
      { id: 115, city: "El Nido", type: "Monthly Rentals" },
      { id: 116, city: "Milford-on-Sea", type: "Monthly Rentals" },
      { id: 117, city: "Albufeira", type: "Holiday rentals" },
      { id: 118, city: "Olhão", type: "House rentals" },
      { id: 119, city: "Herne Bay", type: "House rentals" },
      { id: 120, city: "Ucluelet", type: "Holiday rentals" },
      { id: 121, city: "Littlehampton", type: "Cottage rentals" },
      { id: 122, city: "Bacvice Beach", type: "Villa rentals" },
      { id: 123, city: "Casablanca", type: "Holiday rentals" },
      { id: 124, city: "Porthcawl", type: "Cottage rentals" },
      { id: 125, city: "Chesil Bank", type: "Flat rentals" },
      { id: 126, city: "Victoria", type: "Cottage rentals" },
      { id: 127, city: "Paignton", type: "Holiday rentals" },
      { id: 128, city: "Ksamil", type: "House rentals" },
      { id: 129, city: "Faro", type: "Serviced apartment rentals" },
      { id: 130, city: "Rothesay", type: "Cottage rentals" }
    ]
  },
  {
    id: 3,
    name: "Historic",
    key: "historic",
    items: [
      { id: 201, city: "Hadrian's Wall", type: "Holiday rentals" },
      { id: 202, city: "Alhambra", type: "Pet-friendly rentals" },
      { id: 203, city: "Scone Palace", type: "Holiday rentals" },
      { id: 204, city: "Sudeley Castle", type: "Holiday rentals" },
      { id: 205, city: "Chatsworth House", type: "Pet-friendly rentals" },
      { id: 206, city: "Meteora", type: "Holiday rentals" },
      { id: 207, city: "Pontcysyllte Aqueduct and Ca...", type: "Holiday rentals" },
      { id: 208, city: "Lindisfarne Castle", type: "Holiday rentals" },
      { id: 209, city: "Blenheim Palace", type: "Cottage rentals" },
      { id: 210, city: "Campo de' Fiori", type: "Holiday rentals" },
      { id: 211, city: "Trinity College Dublin", type: "Holiday rentals" },
      { id: 212, city: "Rochester Castle", type: "Holiday rentals" },
      { id: 213, city: "Southwark Park", type: "Holiday rentals" },
      { id: 214, city: "Hanley Swan", type: "Holiday rentals" },
      { id: 215, city: "Koutoubia Mosque", type: "Holiday rentals" },
      { id: 216, city: "Ashton Court Estate", type: "Holiday rentals" },
      { id: 217, city: "Shrewsbury", type: "House rentals" },
      { id: 218, city: "Talmont-Saint-Hilaire", type: "Pet-friendly rentals" },
      { id: 219, city: "Wādī Mūsá", type: "Holiday rentals" },
      { id: 220, city: "Plaza Mayor", type: "Serviced apartment rentals" },
      { id: 221, city: "Neuschwanstein Castle", type: "House rentals" },
      { id: 222, city: "Leeds Castle", type: "Holiday rentals" },
      { id: 223, city: "Burgh Castle", type: "Holiday rentals" },
      { id: 224, city: "Acropolis", type: "Flat rentals" },
      { id: 225, city: "Caldicot", type: "Holiday rentals" },
      { id: 226, city: "Nizwa", type: "House rentals" },
      { id: 227, city: "Edinburgh Castle", type: "Serviced apartment rentals" },
      { id: 228, city: "Old Town Square", type: "Flat rentals" },
      { id: 229, city: "Cardiff Castle", type: "Flat rentals" },
      { id: 230, city: "Fountains Abbey", type: "Holiday rentals" },
      { id: 231, city: "The Iron Bridge", type: "House rentals" },
      { id: 232, city: "Alnwick Castle", type: "Flat rentals" },
      { id: 233, city: "Nyhavn", type: "Holiday rentals" },
      { id: 234, city: "Pantheon", type: "House rentals" },
      { id: 235, city: "Parc dels Auditoris", type: "Holiday rentals" },
      { id: 236, city: "Conwy Castle", type: "Holiday rentals" }
    ]
  },
  {
    id: 4,
    name: "Islands",
    key: "islands",
    items: [
      { id: 301, city: "Epinay-sur-Seine", type: "Apartment rentals" },
      { id: 302, city: "San Lucas Sacatepequez", type: "House rentals" },
      { id: 303, city: "Simbach am Inn", type: "Monthly Rentals" },
      { id: 304, city: "Papeete", type: "Flat rentals" },
      { id: 305, city: "Gili Islands", type: "Holiday rentals" },
      { id: 306, city: "Aka-shima", type: "Holiday rentals" },
      { id: 307, city: "Praia da Ilha de Tavira", type: "Holiday rentals" },
      { id: 308, city: "Ibiúna", type: "Holiday rentals" },
      { id: 309, city: "Palm Jumeirah", type: "Holiday rentals" },
      { id: 310, city: "Pego", type: "Monthly Rentals" },
      { id: 311, city: "Vulcano Porto", type: "Holiday rentals" },
      { id: 312, city: "Maupiti", type: "Holiday rentals" },
      { id: 313, city: "Miranda", type: "Flat rentals" },
      { id: 314, city: "Biała Podlaska", type: "Monthly Rentals" },
      { id: 315, city: "Cérans-Foulletourte", type: "House rentals" },
      { id: 316, city: "Spinalonga", type: "Holiday rentals" },
      { id: 317, city: "Chios", type: "Monthly Rentals" },
      { id: 318, city: "Ilha Da Gigoia", type: "Monthly Rentals" },
      { id: 319, city: "Borromean Islands", type: "Villa rentals" },
      { id: 320, city: "Mellingen", type: "Monthly Rentals" },
      { id: 321, city: "Smith Island", type: "Monthly Rentals" },
      { id: 322, city: "Hilbre Island", type: "House rentals" },
      { id: 323, city: "Carabao Island", type: "Monthly Rentals" },
      { id: 324, city: "La Punt-Chamues-ch", type: "Monthly Rentals" },
      { id: 325, city: "Cunit", type: "Flat rentals" },
      { id: 326, city: "Thousand Islands National Park", type: "Monthly Rentals" },
      { id: 327, city: "Avery Island", type: "Holiday rentals" },
      { id: 328, city: "Madh Island", type: "Holiday rentals" },
      { id: 329, city: "Oued Laou", type: "Flat rentals" },
      { id: 330, city: "Caye Caulker", type: "Monthly Rentals" },
      { id: 331, city: "Ortygia", type: "House rentals" },
      { id: 332, city: "Divar Island", type: "Holiday rentals" },
      { id: 333, city: "Bielawa", type: "Holiday rentals" },
      { id: 334, city: "Babylon", type: "Monthly Rentals" },
      { id: 335, city: "Mahina", type: "House rentals" },
      { id: 336, city: "Fulidhoo", type: "Holiday rentals" }
    ]
  },
  {
    id: 5,
    name: "Lakes",
    key: "lakes",
    items: [
      { id: 401, city: "Locarno", type: "Pet-friendly rentals" },
      { id: 402, city: "Milwaukee", type: "House rentals" },
      { id: 403, city: "Füssen", type: "Flat rentals" },
      { id: 404, city: "Lake Havasu City", type: "Holiday rentals" },
      { id: 405, city: "Austin", type: "Villa rentals" },
      { id: 406, city: "Zürich", type: "Villa rentals" },
      { id: 407, city: "Haugesund", type: "Pet-friendly rentals" },
      { id: 408, city: "Woodstock", type: "Cottage rentals" },
      { id: 409, city: "Montreux", type: "Holiday rentals" },
      { id: 410, city: "Orlando", type: "Flat rentals" },
      { id: 411, city: "St. Petersburg", type: "Cottage rentals" },
      { id: 412, city: "Inveraray", type: "Pet-friendly rentals" },
      { id: 413, city: "Balloch", type: "House rentals" },
      { id: 414, city: "Klagenfurt am Wörthersee", type: "Flat rentals" },
      { id: 415, city: "Panajachel", type: "Villa rentals" },
      { id: 416, city: "Barmouth", type: "Holiday rentals" },
      { id: 417, city: "Bideford", type: "Holiday rentals" },
      { id: 418, city: "Ithaca", type: "Pet-friendly rentals" },
      { id: 419, city: "Heacham", type: "Cottage rentals" },
      { id: 420, city: "Daly City", type: "Holiday rentals" },
      { id: 421, city: "Spiez", type: "Pet-friendly rentals" },
      { id: 422, city: "Tintagel", type: "Cottage rentals" },
      { id: 423, city: "Kyoto", type: "Holiday rentals" },
      { id: 424, city: "St. Catharines", type: "House rentals" },
      { id: 425, city: "Oklahoma City", type: "Pet-friendly rentals" },
      { id: 426, city: "Otsu", type: "House rentals" },
      { id: 427, city: "Buffalo", type: "Pet-friendly rentals" },
      { id: 428, city: "Erie", type: "Cottage rentals" },
      { id: 429, city: "Monnickendam", type: "Flat rentals" },
      { id: 430, city: "Davenport", type: "Flat rentals" }
    ]
  },
  {
    id: 6,
    name: "Things to do",
    key: "things_to_do",
    items: [
      { id: 501, city: "Durham", type: "Outdoors" },
      { id: 502, city: "Cariati", type: "Museums" },
      { id: 503, city: "Norfolk", type: "Outdoors" },
      { id: 504, city: "Great Britain", type: "Food tours" },
      { id: 505, city: "Apennine Mountains", type: "Wildlife" },
      { id: 506, city: "Seine", type: "Outdoors" },
      { id: 507, city: "Paris", type: "Shopping and fashion" },
      { id: 508, city: "Taranto", type: "Tastings" },
      { id: 509, city: "Thames River", type: "Food tours" },
      { id: 510, city: "London", type: "Cultural tours" },
      { id: 511, city: "7th Arrondissement", type: "Things to do" },
      { id: 512, city: "16th Arrondissement", type: "Things to do" },
      { id: 513, city: "City of Westminster", type: "Outdoors" },
      { id: 514, city: "Rome", type: "Food tours" },
      { id: 515, city: "Oued Tensift", type: "Dining" },
      { id: 516, city: "Medina", type: "Things to do" },
      { id: 517, city: "Francavilla al Mare", type: "Dining" },
      { id: 518, city: "Elgin", type: "Landmarks" },
      { id: 519, city: "Honshu", type: "Art workshops" },
      { id: 520, city: "Porto", type: "Food tours" },
      { id: 521, city: "Sea of the Hebrides", type: "Landmarks" },
      { id: 522, city: "Nomós Kykládon", type: "Tastings" },
      { id: 523, city: "Regent's Canal", type: "Tastings" },
      { id: 524, city: "London Borough of Lambeth", type: "Performances" },
      { id: 525, city: "Arcozelo", type: "Cooking" },
      { id: 526, city: "Cythera", type: "Art workshops" },
      { id: 527, city: "Lambeth", type: "Things to do" },
      { id: 528, city: "Saronic Islands", type: "Water sports" },
      { id: 529, city: "Regional Unit of Islands", type: "Art workshops" },
      { id: 530, city: "East Attica Regional Unit", type: "Landmarks" }
    ]
  }
];